// Tech Stack Modal Logic
function showTechStack() {
  document.getElementById('techModal').classList.add('show');
}
function closeTechStack() {
  document.getElementById('techModal').classList.remove('show');
}
window.onclick = function(event) {
  if (event.target == document.getElementById('techModal')) {
    closeTechStack();
  }
}

// Export Logic
function exportItem(type) {
  const content = "SIMULATED EXPORT: " + type + "\n\n[Data dynamically generated by Flask-RESTful API in production...]";
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "export_" + type.replace(/ /g, "_").toLowerCase() + ".txt";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  alert("Exporting: " + type + "...");
}

// Function to generate a random mock SHA-256 hash
function generateMockHash() {
  const chars = '0123456789abcdef';
  let hash = '';
  for(let i=0; i<64; i++) {
    hash += chars[Math.floor(Math.random() * chars.length)];
  }
  return hash;
}

// Initial dummy logs representing full audit trail
let custodyLogs = [
  { 
    evId: 'EVID-10492', caseId: 'CAS-9824', name: 'Server Traffic PCAP', type: 'PCAP File',
    size: '450 MB', investigator: 'Agent 007', device: 'Wireshark Node 3',
    srcIp: '192.168.1.10', dstIp: '10.0.0.5', method: 'Deep Packet Inspection (DPI)',
    location: 'Secure Vault Sector 4', notes: 'High Priority',
    action: 'COLLECTED AT SCENE', time: '2026-07-18 14:32:01', hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    audit: { createdBy: 'SYSTEM', uploadedBy: 'Agent 007', integrity: 'VERIFIED' }
  }
];

const ledgerList = document.getElementById('ledgerList');

function renderLog(log) {
  const div = document.createElement('div');
  div.className = 'log-entry';
  
  let actionColor = 'var(--cyan)';
  
  div.innerHTML = `
    <div class="log-header">
      <span class="log-case"><i class='bx bx-fingerprint'></i> ${log.evId} | ${log.caseId}</span>
      <span class="log-time">${log.time}</span>
    </div>
    <div class="log-action" style="color: ${actionColor}">[ EVIDENCE ${log.action} ]</div>
    
    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px; font-size: 12px; margin-bottom: 10px; background: rgba(0,0,0,0.3); padding: 10px; border-radius: 4px;">
      <div><strong>Name:</strong> ${log.name}</div>
      <div><strong>Type:</strong> ${log.type} (${log.size})</div>
      <div><strong>Device:</strong> ${log.device}</div>
      <div><strong>Method:</strong> ${log.method}</div>
      <div><strong>Source:</strong> ${log.srcIp}</div>
      <div><strong>Dest:</strong> ${log.dstIp}</div>
      <div><strong>Location:</strong> ${log.location}</div>
      <div><strong>Notes:</strong> ${log.notes}</div>
    </div>
    
    <div style="font-size: 11px; color: rgba(255,255,255,0.5); margin-bottom: 10px;">
      <em>Audit Trail: Uploaded by ${log.audit.uploadedBy} | Integrity: ${log.audit.integrity}</em>
    </div>
    <div class="log-hash">SHA-256: ${log.hash}</div>
  `;
  
  ledgerList.insertBefore(div, ledgerList.firstChild);
}

function initLedger() {
  ledgerList.innerHTML = '';
  custodyLogs.forEach(log => renderLog(log));
}

function addLog() {
  const evId = document.getElementById('evId').value || 'EVID-UNKNOWN';
  const caseId = document.getElementById('evCaseId').value || 'CAS-UNKNOWN';
  const name = document.getElementById('evName').value || 'Unnamed Evidence';
  const type = document.getElementById('evType').value;
  const size = document.getElementById('evSize').value || 'Unknown';
  const investigator = document.getElementById('evInvestigator').value || 'Unknown Agent';
  const device = document.getElementById('evDevice').value || 'Unknown Device';
  const srcIp = document.getElementById('evSrcIp').value || 'N/A';
  const dstIp = document.getElementById('evDstIp').value || 'N/A';
  const method = document.getElementById('evMethod').value;
  const location = document.getElementById('evLocation').value || 'Unknown Location';
  const notes = document.getElementById('evNotes').value || 'None';
  
  const now = new Date();
  const time = now.toISOString().replace('T', ' ').substring(0, 19);
  
  const newLog = {
    evId, caseId, name, type, size, investigator, device, srcIp, dstIp, method, location, notes,
    action: 'REGISTERED IN CUSTODY', time, hash: generateMockHash(),
    audit: { createdBy: 'SYSTEM', uploadedBy: investigator, integrity: 'VERIFIED' }
  };
  
  custodyLogs.push(newLog);
  renderLog(newLog);
}

function filterLedger() {
  const term = document.getElementById('searchAudit').value.toLowerCase();
  ledgerList.innerHTML = '';
  custodyLogs.filter(log => log.hash.toLowerCase().includes(term) || log.evId.toLowerCase().includes(term) || log.caseId.toLowerCase().includes(term)).forEach(log => renderLog(log));
}

initLedger();
