import re

with open('frontend/modules/malware/js/dfir.js', 'r', encoding='utf-8') as f:
    js_content = f.read()

# Fix the rest of the broken HTML tags that PowerShell stripped quotes from
js_content = js_content.replace('apiList.innerHTML = <li class="empty-list">No suspicious APIs detected</li>;',
                                'apiList.innerHTML = \'<li class="empty-list">No suspicious APIs detected</li>\';')

js_content = js_content.replace('mitreGrid.innerHTML = an.mitre.map(m => <div class="mitre-card"><span class="mitre-id"> + m.id + </span><div class="mitre-name"> + m.name + </div><div class="mitre-desc"> + m.desc + </div></div>).join(\'\');',
                                'mitreGrid.innerHTML = an.mitre.map(m => \'<div class="mitre-card"><span class="mitre-id">\' + m.id + \'</span><div class="mitre-name">\' + m.name + \'</div><div class="mitre-desc">\' + m.desc + \'</div></div>\').join(\'\');')

js_content = js_content.replace('mitreGrid.innerHTML = <div class="empty-list">No MITRE tactics mapped.</div>;',
                                'mitreGrid.innerHTML = \'<div class="empty-list">No MITRE tactics mapped.</div>\';')

js_content = js_content.replace('document.getElementById(\'ai-report-body\').innerHTML = <div class="ai-report"><h3>EXECUTIVE SUMMARY</h3><p>The analyzed executable <strong> + file.filename + </strong> exhibits an entropy of  + an.entropy +  and utilizes  + (an.apis ? an.apis.length : 0) +  suspicious APIs. Risk score assessed at  + riskScore.toFixed(1) + /10.</p><p style="color:var(--cyan); margin-top:20px; font-family:\'JetBrains Mono\'">Report Generated by JusticeFlowX AI Engine</p></div>;',
                                'document.getElementById(\'ai-report-body\').innerHTML = \'<div class="ai-report"><h3>EXECUTIVE SUMMARY</h3><p>The analyzed executable <strong>\' + file.filename + \'</strong> exhibits an entropy of \' + an.entropy + \' and utilizes \' + (an.apis ? an.apis.length : 0) + \' suspicious APIs. Risk score assessed at \' + riskScore.toFixed(1) + \'/10.</p><p style="color:var(--cyan); margin-top:20px; font-family:\\\'JetBrains Mono\\\'">Report Generated by JusticeFlowX AI Engine</p></div>\';')

js_content = js_content.replace('nwBehaviors.innerHTML = an.behaviors.map(b => <div class="behavior-item  + (b.danger ? \'danger\' : \'\') + "><div class="behavior-title"> + b.title + </div><div class="behavior-desc"> + b.desc + </div></div>).join(\'\');',
                                'nwBehaviors.innerHTML = an.behaviors.map(b => \'<div class="behavior-item \' + (b.danger ? \\\'danger\\\' : \\\'\\\') + \'"><div class="behavior-title">\' + b.title + \'</div><div class="behavior-desc">\' + b.desc + \'</div></div>\').join(\'\');')

js_content = js_content.replace('nwBehaviors.innerHTML = <div class="empty-list" style="margin-top: 40px; text-align:center;">No suspicious network behaviors detected.</div>;',
                                'nwBehaviors.innerHTML = \'<div class="empty-list" style="margin-top: 40px; text-align:center;">No suspicious network behaviors detected.</div>\';')

js_content = js_content.replace('iocTable.innerHTML = an.iocs.map(ioc => <tr><td><span style="background:rgba(0,210,255,0.2); padding:2px 6px; border-radius:4px;"> + ioc.type + </span></td><td class="mono"> + ioc.value + </td><td class="text-red"> + ioc.reputation + </td><td>Just now</td></tr>).join(\'\');',
                                'iocTable.innerHTML = an.iocs.map(ioc => \'<tr><td><span style="background:rgba(0,210,255,0.2); padding:2px 6px; border-radius:4px;">\' + ioc.type + \'</span></td><td class="mono">\' + ioc.value + \'</td><td class="text-red">\' + ioc.reputation + \'</td><td>Just now</td></tr>\').join(\'\');')

js_content = js_content.replace('document.getElementById(\'ai-report-body\').innerHTML = <div class="ai-report"><h3>EXECUTIVE SUMMARY</h3><p>The analyzed PCAP file <strong> + file.filename + </strong> exhibits  + (an.behaviors ? an.behaviors.length : 0) +  anomalies.</p><p style="color:var(--cyan); margin-top:20px; font-family:\'JetBrains Mono\'">Report Generated by JusticeFlowX AI Engine</p></div>;',
                                'document.getElementById(\'ai-report-body\').innerHTML = \'<div class="ai-report"><h3>EXECUTIVE SUMMARY</h3><p>The analyzed PCAP file <strong>\' + file.filename + \'</strong> exhibits \' + (an.behaviors ? an.behaviors.length : 0) + \' anomalies.</p><p style="color:var(--cyan); margin-top:20px; font-family:\\\'JetBrains Mono\\\'">Report Generated by JusticeFlowX AI Engine</p></div>\';')

# Since it might be hard to match exact whitespace after powershell manipulation, let's just use regex to fix the backticks.
# Actually, the best way to fix this completely mangled file is to just rewrite the function block using write_to_file.

